MoDeNa: applications/PUfoam/MoDeNaModels/CFD_tool_0D/src/bubbleRadius.h File Reference
bubbleRadius.h File Reference
Models » 0-D CFD Model
functions related to the calculations of bubble radius.
Functions
bool isNaN (double var)
checks if the passed argument is not a number
double bubbleRadius (const double m0, const double m1)
radius of bubbles based on the moments
double nodeRadius (const double &v)
radius of bubbles at each node
Detailed Description
functions related to the calculations of bubble radius.
Definition in file bubbleRadius.h.
Function Documentation
bubbleRadius()
double bubbleRadius (const double m0, const double m1)
radius of bubbles based on the moments
radius of bubbles based on moments
Parameters
m0 moment of order zero
m1 moment of order one
Returns
bubble radius
Definition at line 28 of file bubbleRadius.h.
References init_size, and isNaN().
Referenced by partialPressureBA(), and partialPressureCO2().
isNaN()
bool isNaN (double var)
checks if the passed argument is not a number
checks if the input is valid
Parameters
var input variable
Returns
true, if the argument is NaN
Parameters
var input variable
Returns
true if the value is valid
Definition at line 23 of file bubbleRadius.h.
References globals::d.
Referenced by bubbleRadius().
nodeRadius()
double nodeRadius (const double & v)
radius of bubbles at each node
bubble radius at the node
Parameters
v volume of bubble
Returns
radius of bubble at the node
Parameters
v bubble volume
Returns
bubble radius
Definition at line 38 of file bubbleRadius.h.
Referenced by thermalDiffusivityGas().