MoDeNa: applications/PUfoam/MoDeNaModels/CFD_tool_3D/src/KineticsFunctions.H File Reference
KineticsFunctions.H File Reference
Models » 3-D CFD Model
functions for kinetics calculations
Functions
double LliqMax (double &)
maximum allowable amount of liquid blowing agent (n-pentane) in liquid
double ddT_LliqMax (double &)
derivative of LliqMax with respect to temperature
double arrhenius (double &, double &, double &)
Arrhenius function.
double BAdilution (double &, double &, double &)
dilution term for the blowing agent (n-pentane)
double QKinW (double &, double &, double &, double &, double &, double &, double &)
double henryCoefficient (double &T)
Henry coefficient for CO2.
double bubbleRadius (const double m0, const double m1)
double partialPressureCO2 (double &M_CO2, double &M_B, double &surfaceTension, double &wCO2_g, double &wBA_g, double &p, double &R)
partial pressure of CO2
double partialPressureBA (double &M_B, double &M_CO2, double &surfaceTension, double &wBA_g_val, double &wCO2_g_val, double &prsr, double &bubble_radius)
partial pressure of blowing agent
double wCO2Max (double &M_CO2, double &M_liq, double &pCO2, double &henryCoeff)
dissolved amount of CO2 in liquid
double xBL (double &T, double &dxdT)
mole fraction of blowing agent (R-11) in liquid polymer
double wBL_D (double &xBL, double &M_B, double &M_NCO, double &L0)
weight fraction of maximum allowable blowing agent (R-11) in liquid
double LmaxR11 (double &tmptr)
double creamTemperature (double &xBL0, double &dxdT)
criticall temperature that foaming process starts
double dTdtFirstOrder (double &Tc, double &To, double &timeStep)
first order accurate dTdt
double dTdtSecondOrder (double &Tc, double &To, double &Too, double &timeStep)
second order accurate dTdt
double thermalDiffusivityGas (double &T)
thermal diffusivity of gas as a function of temperature
double nodeRadius (const double &v)
double QKinW (double &AW, double &EW, double &tempi, double &Lliq, double &rhoPoly, double &rhoBL)
arrhenius term times by dilution term
Detailed Description
functions for kinetics calculations
Definition in file KineticsFunctions.H.
Function Documentation
arrhenius()
double arrhenius (double & AOH, double & EOH, double & tempt)
Arrhenius function.
Parameters
AOH pre-exponential factor
EOH activation energy
tempt temperature
Returns
arrhenius value
Definition at line 164 of file KineticsFunctions.H.
BAdilution()
double BAdilution (double & L_l, double & rhoPoly, double & rhoBL)
dilution term for the blowing agent (n-pentane)
Parameters
L_l weight fraction of liquid blowing agent
rhoPoly density of liquid mixture (polymer)
rhoBL density of blowing agent
Returns
dilution term
Definition at line 170 of file KineticsFunctions.H.
References QKinW().
creamTemperature()
double creamTemperature (double & xBL0, double & dxdT)
criticall temperature that foaming process starts
Parameters
xBL0 initial mole fraction of the blowing agent (R-11)
dxdT constant
Returns
cream temperature
Definition at line 323 of file KineticsFunctions.H.
ddT_LliqMax()
double ddT_LliqMax (double & tmptr)
derivative of LliqMax with respect to temperature
Parameters
tmptr input temperature
Returns
value of derivative for input temperature
Definition at line 156 of file KineticsFunctions.H.
dTdtFirstOrder()
double dTdtFirstOrder (double & Tc, double & To, double & timeStep)
first order accurate dTdt
Parameters
Tc current value of temperature
To old value of temperature
timeStep time step
Returns
first order derivative
Definition at line 328 of file KineticsFunctions.H.
dTdtSecondOrder()
double dTdtSecondOrder (double & Tc, double & To, double & Too, double & timeStep)
second order accurate dTdt
Parameters
Tc current value of temperature
To old value of temperature
Too old-old value of temperature
timeStep time step
Returns
second order derivative
Definition at line 332 of file KineticsFunctions.H.
henryCoefficient()
double henryCoefficient (double & T)
Henry coefficient for CO2.
Parameters
T temperature
Returns
Henry coefficient
Definition at line 185 of file KineticsFunctions.H.
LliqMax()
double LliqMax (double & tmptr)
maximum allowable amount of liquid blowing agent (n-pentane) in liquid
Parameters
tmptr input temperature
Returns
equilibrium value of blowing agent in liquid
Definition at line 139 of file KineticsFunctions.H.
partialPressureBA()
double partialPressureBA (double & M_B, double & M_CO2, double & surfaceTension, double & wBA_g_val, double & wCO2_g_val, double & prsr, double & bubble_radius)
partial pressure of blowing agent
Parameters
M_B molecular weight of blowing agent
M_CO2 molecular weight of CO2
surfaceTension surface tension
wBA_g weight fraction of blowing agent in gas
wCO2_g weight fraction of CO2 in gas
p ambient pressure
R bubble radius
Returns
partial pressure of blowing agent
Definition at line 239 of file KineticsFunctions.H.
References M_B.
partialPressureCO2()
double partialPressureCO2 (double & M_CO2, double & M_B, double & surfaceTension, double & wCO2_g, double & wBA_g, double & p, double & R)
partial pressure of CO2
Parameters
M_CO2 molecular weight of CO2
M_B molecular weight of blowing agent
surfaceTension surface tension
wCO2_g weight fraction of CO2 in gas
wBA_g weight frcation of blowing agent in gas
p ambient pressure
R bubble radius
Returns
partial pressure of CO2
Definition at line 218 of file KineticsFunctions.H.
QKinW()
QKinW (double & AW, double & EW, double & tempi, double & Lliq, double & rhoPoly, double & rhoBL)
arrhenius term times by dilution term
Parameters
AW pre-exponential factor
EW activation energy
tempi temperature
Lliq weight fraction of liquid blowing agent
rhoPoly density of liquid mixture (polymer)
rhoBL density of blowing agent
Returns
source term
Definition at line 176 of file KineticsFunctions.H.
Referenced by BAdilution().
thermalDiffusivityGas()
double thermalDiffusivityGas (double & T)
thermal diffusivity of gas as a function of temperature
Parameters
T temperature
Returns
thermal diffusivity of gas
Definition at line 337 of file KineticsFunctions.H.
References nodeRadius().
wBL_D()
double wBL_D (double & xBL, double & M_B, double & M_NCO, double & L0)
weight fraction of maximum allowable blowing agent (R-11) in liquid
Parameters
xBL mole fraction of blowing agent (R-11)
M_B molecular weight of blowing agent (R-11)
M_NCO molecular weight of NCO
Returns
maximum solubility of R-11 in liquid
Definition at line 294 of file KineticsFunctions.H.
References M_NCO, and xBL().
wCO2Max()
double wCO2Max (double & M_CO2, double & M_liq, double & pCO2, double & henryCoeff)
dissolved amount of CO2 in liquid
Parameters
M_CO2 molecular weight of CO2
M_liq molecular weight of liquid mixture
pCO2 partial pressure of CO2
henryCoeff Henry coefficient
Returns
maximum solubility of CO2 in liquid
Definition at line 260 of file KineticsFunctions.H.
xBL()
double xBL (double & T, double & dxdT)
mole fraction of blowing agent (R-11) in liquid polymer
Parameters
T temperature
dxdT model constant
Returns
mole fraction of R-11 in liquid
Definition at line 275 of file KineticsFunctions.H.
Referenced by wBL_D().