MoDeNa: applications/PUfoam/MoDeNaModels/FoamConstruction/foamreconstr/src/geometry.cc File Reference
geometry.cc File Reference
Models » Foam Construction Module » C++ Source Code
Helpful geometric and mathematical functions.
#include "globals.hh"
Functions
bool in_domain (double x, double y, double z)
True if the point is in the domain, False otherwise.
double * CrossProduct (double a[], double b[])
Cross product of two points in 3D.
bool SameSide (double p1[], double p2[], double a[], double b[])
True if two points are in the same half-plane defined by other two points.
bool PointInTriangle (double p[], double a[], double b[], double c[])
True if point lies in the triangle.
double porosity (int ***amat)
Calculates porosity.
Detailed Description
Helpful geometric and mathematical functions.
Author
Pavel Ferkl
Definition in file geometry.cc.
Function Documentation
CrossProduct()
double* CrossProduct (double a[], double b[])
Cross product of two points in 3D.
Parameters
[in] a 1st point
[in] b 2nd point
Definition at line 20 of file geometry.cc.
References globals::cp.
Referenced by SameSide().
in_domain()
bool in_domain (double x, double y, double z)
True if the point is in the domain, False otherwise.
Parameters
[in] x x position
[in] y x position
[in] z x position
Definition at line 9 of file geometry.cc.
References globals::nz.
Referenced by importFoamSkeleton(), makeEdgeStruts(), makeNodeStruts(), and saveToGnuplot().
PointInTriangle()
bool PointInTriangle (double p[], double a[], double b[], double c[])
True if point lies in the triangle.
Parameters
[in] p the point
[in] a 1st point defining triangle
[in] b 2nd point defining triangle
[in] c 3rd point defining triangle
Definition at line 56 of file geometry.cc.
Referenced by makeEdgeStruts().
porosity()
double porosity (int *** amat)
Calculates porosity.
Parameters
[in] amat matrix
Definition at line 70 of file geometry.cc.
References globals::nx, globals::ny, globals::nz, and constants::por.
Referenced by main(), and phys_prop::porosity().
SameSide()
bool SameSide (double p1[], double p2[], double a[], double b[])
True if two points are in the same half-plane defined by other two points.
Parameters
[in] p1 1st point
[in] p2 2nd point
[in] a 1st point defining half-plane
[in] b 2nd point defining half-plane
Definition at line 32 of file geometry.cc.
References CrossProduct().