MoDeNa: globals Module Reference
globals Module Reference
namespace with global variables
Variables
character(len=99) fileplacein
location of input files
character(len=99) fileplaceout
location of output files
character(len=99) inputs
input file
character(len=99) outputs_1d
output file with scalar variables
character(len=99) outputs_gr
output file for the surrogate model fitting
character(len=99) outputs_c
output file with concentration profiles
character(len=99) outputs_kin
output file with variables of detailed kinetic model
character(len=99) outputs_drain
output file for the wall drainage
character(len=99) outputs_af
final foam properties for foam cond. and foam aging
character(len=99) geometry
geometry 3D=spherical, 2D=cylindrical
logical inertial_term
include inertial term in equations (t/f)
logical solcorr
use solubility correction on bubble radius (t/f)
logical surfactantpresent
surfactant is present - pcsaft caluclation (t/f)
logical gelpoint
gel point reached (t/f)
logical dilution
use dilution effect for kinetics (t/f)
logical shooting
am I using shooting method (t/f)
integer fi1
integer fi2
integer fi3
integer fi4
integer fi5
file indices
integer integrator
integrator. 1=dlsode,2=dlsodes
integer int_meth
stiff or no? See MF for ODEPACK
integer p
number of internal nodes
integer maxts
maximum inner time steps between t and t+h
integer its
number of outer integration outer time steps
integer visc_model
viscosity model. 1=constant,2=Castro and Macosko,3=modena
integer rhop_model
polymer density model. 1=constant,2=modena
integer itens_model
interfacial tension model. 1=constant,2=modena
integer kin_model
reaction kinetics model.
integer ngas
number of dissolved gases
integer co2_pos
carbon dioxide position
integer fceq
first concentration equation (index)
integer fpeq
first pressure equation (index)
integer lpeq
last pressure equation (index)
integer req
radius equation (index)
integer teq
temperature equation (index)
integer xoheq
polyol conversion equation (index)
integer xweq
water conversion equation (index)
real(dp) mshco
mesh coarsening parameter
real(dp) temp0
initial temperature
real(dp) r0
initial radius
real(dp) nb0
initial bubble number density
real(dp) sn
how many times is initial shell larger than initial bubble radius
real(dp) oh0
initial concentration of polyol (don't set to zero)
real(dp) w0
initial concentration of water (can be zero)
real(dp) nco0
initial concentration of isocyanate
real(dp) catalyst
concentration of catalyst
real(dp) polyol1_ini
initial concentration of polyol 1
real(dp) polyol2_ini
initial concentration of polyol 2
real(dp) amine_ini
initial concentration of amine
real(dp) isocyanate1_ini
initial concentration of isocyanate 1
real(dp) isocyanate2_ini
initial concentration of isocyanate 2
real(dp) isocyanate3_ini
initial concentration of isocyanate 3
real(dp) aoh
frequential factor of gelling reaction
real(dp) eoh
activation energy of gelling reaction
real(dp) aw
frequential factor of blowing reaction
real(dp) ew
activation energy of blowing reaction
real(dp) dhoh
gelling reaction enthalpy
real(dp) dhw
blowing reaction enthalpy
real(dp) time
time (s)
real(dp) radius
bubble radius (m)
real(dp) laplace_pres
Laplace pressure (Pa)
real(dp) eqconc
equivalent concentration for first gas
real(dp), dimension(2) grrate
growth rate
real(dp) st
shell thickness
real(dp) s0
initial shell thickness
real(dp) rel_tol
relative tolerance
real(dp) abs_tol
absolute tolerance
real(dp) eta
viscosity
real(dp) pamb
ambient pressure (in the liquid)
real(dp) sigma
interfacial tension
real(dp) rhop
polymer density
real(dp) cp
heat capacity of the reaction mixture
real(dp) cppol
heat capacity of polymer
real(dp) rhobl
density of liquid physical blowing agent
real(dp) porosity
foam porosity
real(dp) rhofoam
foam density
real(dp) pair0
initial partial pressure of air
real(dp) pair
partial pressure of air
real(dp) timestep
timestep
real(dp) goalradius
final radius we want to achieve
real(dp), dimension(2) nold
moles in bubble
real(dp) vsh
shell volume
real(dp) temp
temperature (K)
real(dp) conv
conversion of polyol
real(dp) gelpointconv
conversion of polyol at gel point
real(dp) rey
Reynolds number.
real(dp) pairst
non-dimensional air pressure
real(dp) pambst
non-dimensional ambient pressure
real(dp) ca
capillary number
integer, dimension(:), allocatable diff_model
diffusivity model 1=constant,2=modena
integer, dimension(:), allocatable sol_model
solubility model 1=constant,2=modena
integer, dimension(:), allocatable kineq
kinetics state variable equations (indexes)
real(dp), dimension(:), allocatable y
state variables
real(dp), dimension(:), allocatable cbl
concentration profile in reaction mixture
real(dp), dimension(:), allocatable xgas
initial molar fraction of gases in the bubble
real(dp), dimension(:), allocatable kinsource
kinetic source term
real(dp), dimension(:), allocatable d
diffusion coefficients (for each dissolved gas)
real(dp), dimension(:), allocatable d0
initial diffusion coefficients used in non-dimensional routines
real(dp), dimension(:), allocatable kh
Henry constants (for each dissolved gas)
real(dp), dimension(:), allocatable mbl
blowing agent molar mass (for each dissolved gas)
real(dp), dimension(:), allocatable dhv
evaporation heat of blowing agent (for each gas)
real(dp), dimension(:), allocatable cpblg
heat capacity of blowing agent in gas phase (for each gas)
real(dp), dimension(:), allocatable cpbll
heat capacity of blowing agent in liquid phase (for each gas)
real(dp), dimension(:), allocatable mb
moles in polymer
real(dp), dimension(:), allocatable mb2
moles in bubble
real(dp), dimension(:), allocatable mb3
total moles
real(dp), dimension(:), allocatable avconc
average concentration in reaction mixture
real(dp), dimension(:), allocatable pressure
partial pressure(Pa)
real(dp), dimension(:), allocatable wblpol
weight fraction of blowing agents in reaction mixture
real(dp), dimension(:), allocatable dz
spatial discretization
logical sheet
determines if sheet is used on the outside of the foam
integer nroutputs
number of outer endme steps
integer divwall
number of grid points in wall
integer divcell
number of grid points in cell
integer divsheet
number of grid points in sheet
integer ncell
number of cells
integer, dimension(:), allocatable solmodel
solubility model
integer, dimension(:), allocatable diffmodel
diffusivity model
real(dp) tend
time at the beginning
real(dp) tbeg
time at the end
real(dp) dcell
cell size
real(dp) dwall
wall thickness
real(dp) dfoam
foam thickness
real(dp) dsheet
sheet thickness
real(dp) temp_cond
temperature of conductivity measurements
real(dp) fstrut
strut content
real(dp) rhof
foam density
real(dp) eps
foam porosity
real(dp) dgas
gas diffusivity in gasphase
real(dp), dimension(:), allocatable sg
gas solubility in polymer
real(dp), dimension(:), allocatable dg
gas diffusiviy in polymer
real(dp), dimension(:), allocatable sheetsg
gas solubility in sheet
real(dp), dimension(:), allocatable sheetdg
gas diffusivity in sheet
real(dp), dimension(:), allocatable xg
molar fractions of gases
real(dp), dimension(:), allocatable pbg
boundary conditions
bool createNodes
create struts at cell vertices
bool createEdges
create struts at cell edges
bool openCell
make open cell foam
bool save_dat
save file in old dx style
bool save_vtk
save file in new paraview style
double dstrut
parameter influencing size of struts in cell vertices
double dedge
parameter influencing size of struts in cell edges
double strutPorosity
double RANDOM
int grid
int nx
domain size in X
int ny
domain size in Y
int nz
domain size in Z
int sx
size of cells in X
int sy
size of cells in Y
int sz
size of cells in Z
bool save_voro_diag1
gnuplot Voronoi diagram
bool save_voro_diag2
alternative gnuplot Voronoi diagram
bool import_vtk
import morphology from vtk
bool progress_report
show detailed progress report
character(len=1024) viscositymodel
viscosity model (constant, fromFile)
character(len=1024) growthratemodel
growth rate model (constantGrowth, fromFile)
integer meshpoints
number of discretization points in space
integer int_method
type of integration method (see MF in ODEPACK)
real(dp) strutfilmparameter
parameter determining strut-film boundary
real(dp) hi
film thickness at center
real(dp) rd
computational domain size (radius)
real(dp) rc
total window size (radius)
real(dp) rc0
initial total window size (radius)
real(dp) dr
mesh points spacing
real(dp) mu
viscosity
real(dp) gam
surface tension
real(dp) dstr
where strut starts in initial domain
real(dp) ndp
disjoining pressure constant
real(dp) mdp
disjoining pressure constant
real(dp) cdp
disjoining pressure constant
real(dp) hdp
disjoining pressure constant
real(dp) bdp
disjoining pressure constant, set to zero for no DP
real(dp) gr
growth rate
real(dp) int_reltol
relative tolerance of integrator
real(dp) int_abstol
absolute tolerance of integrator
real(dp) initialtime
starting time
real(dp) ae_tol
tolerance of algebraic equation solver
Detailed Description
namespace with global variables
Variable Documentation
grid
int globals::grid
grid type for cell centers, 1=cubic grid, 2=hexagonal lattice, ABAB...,3=hexagonal lattice, ABCABC...
Definition at line 17 of file globals.cc.
Referenced by createSeeds(), and readParameters().
its
integer globals::its
number of outer integration outer time steps
outer time steps (how many times is output written)
Definition at line 29 of file globals.f90.
Referenced by integration::bblinteg(), integration::preprocess(), in_out::read_inputs(), in_out::save_integration_close(), model::set_initial_conditions(), and phys_prop::set_initial_physical_properties().
maxts
integer globals::maxts
maximum inner time steps between t and t+h
maximum inner time steps
Definition at line 29 of file globals.f90.
Referenced by integration::bblpreproc(), integration::preprocess(), and in_out::read_inputs().
pressure
real(dp) globals::pressure
partial pressure(Pa)
initial pressure
Definition at line 106 of file globals.f90.
Referenced by integration::bblinteg(), model::dim_var(), physicalproperties::gasdiffusivity(), inout::input(), integration::integrate(), model::molar_balance(), in_out::read_inputs(), in_out::save_integration_close(), and in_out::save_integration_step().
RANDOM
double globals::RANDOM
number between 0.0 and 1.0, how much are positions of cell centers perturbated from even position
Definition at line 15 of file globals.cc.
Referenced by createSeeds(), and readParameters().
strutPorosity
double globals::strutPorosity
desired porosity of only struts
Definition at line 14 of file globals.cc.
Referenced by readParameters().
temp
real(dp) globals::temp
temperature (K)
temperature of aging
Definition at line 49 of file globals.f90.
Referenced by integration::bblinteg(), integration::bblpreproc(), model::dim_var(), inout::input(), integration::integrate(), model::molar_balance(), model::odesystem(), inout::output(), inout::print_header(), in_out::save_integration_step(), and phys_prop::set_initial_physical_properties().
timestep
real(dp) globals::timestep
timestep
time step (how often are values written)
Definition at line 49 of file globals.f90.
Referenced by integration::bblinteg(), integration::bblpreproc(), integration::preprocess(), model::set_initial_conditions(), and phys_prop::set_initial_physical_properties().